### PR TITLE
Support extrapolation on all Weyl scalars

### PR DESCRIPTION
**Pull request by 10220**
This does a few things:
- Fixes a bug in the extrapolation procedure (data would have NaN's) 
- Fixes a bug where output wouldn't be printed to non-NRAR format 
- Allows extrapolation to support all Weyl scalars
- Chooses default Lmin based on DataType (i.e. spin-weight)

### CODE REVIEW

**Comment by 10220** [comment]
Hey @moble, everything should be good now. Scri's extrapolation procedure supports VersionHist.ver with the newest commit I added to this PR.

**Comment by markscheel** [comment]
@moble I would like to change the SpEC postprocessing scripts to use scri instead of GWFrames for extrapolation.  Then the scripts (especially a future version that will run as a cron job) will be simpler and will have fewer dependencies. Is there any reason not to do this?  If we want to move from GWFrames to scri, I think we need this PR or some modified version of it.

**Comment by 10220** [comment]
Hey @moble, let me know if there is still any other changes you wanted. Otherwise at this point I think this is all set.

**Comment by 10220** [comment]
Also both conda-forge and pip have the updated versions of quaternion.

**Pull request merged**
