### PR TITLE
Speed up WaveformModes.apply_eth: only one multiply per element

### PR DESCRIPTION
**Pull request by duetosymmetry**
This follows the discussion starting in this PR comment: https://github.com/moble/scri/pull/18#issuecomment-523710834

Also only one square root per value of \ell, but this is relatively minor compared to only one multiply per element.

### CODE REVIEW

**Comment by duetosymmetry** [comment]
@10220 @moble would either of you like to review this PR?

**Comment by duetosymmetry** [comment]
Rebased onto upstream

**Comment by duetosymmetry** [comment]
Rebased so this PR is a fast-forward

**Comment by moble** [comment]
Thanks.  Sorry for the slow reply.  :$

**Pull request merged**
